export interface FacultyThemeConfig {
  id: string;
  name: string;
  hex: string;
  // Clases Tailwind
  bgPrimary: string;
  bgLight: string;
  bgLightHover: string;
  borderLight: string;
  borderPrimary: string;
  hoverBorder: string;
  borderLeft: string;
  textPrimary: string;
  textDark: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  progressFill: string;
  iconBg: string;
  iconText: string;
}

export const FACULTY_THEMES: Record<string, FacultyThemeConfig> = {
  emerald: {
    id: 'emerald',
    name: 'Esmeralda Institucional',
    hex: '#059669',
    bgPrimary: 'bg-emerald-600',
    bgLight: 'bg-emerald-50/70',
    bgLightHover: 'hover:bg-emerald-100/70',
    borderLight: 'border-emerald-200',
    borderPrimary: 'border-emerald-500',
    hoverBorder: 'hover:border-emerald-500',
    borderLeft: 'border-l-emerald-600',
    textPrimary: 'text-emerald-700',
    textDark: 'text-emerald-900',
    badgeBg: 'bg-emerald-100',
    badgeText: 'text-emerald-800',
    badgeBorder: 'border-emerald-300',
    progressFill: 'bg-emerald-600',
    iconBg: 'bg-emerald-100',
    iconText: 'text-emerald-700',
  },
  blue: {
    id: 'blue',
    name: 'Azul Real & TIC',
    hex: '#2563EB',
    bgPrimary: 'bg-blue-600',
    bgLight: 'bg-blue-50/70',
    bgLightHover: 'hover:bg-blue-100/70',
    borderLight: 'border-blue-200',
    borderPrimary: 'border-blue-500',
    hoverBorder: 'hover:border-blue-500',
    borderLeft: 'border-l-blue-600',
    textPrimary: 'text-blue-700',
    textDark: 'text-blue-900',
    badgeBg: 'bg-blue-100',
    badgeText: 'text-blue-800',
    badgeBorder: 'border-blue-300',
    progressFill: 'bg-blue-600',
    iconBg: 'bg-blue-100',
    iconText: 'text-blue-700',
  },
  sky: {
    id: 'sky',
    name: 'Azul Cielo & Datos',
    hex: '#0284C7',
    bgPrimary: 'bg-sky-600',
    bgLight: 'bg-sky-50/70',
    bgLightHover: 'hover:bg-sky-100/70',
    borderLight: 'border-sky-200',
    borderPrimary: 'border-sky-500',
    hoverBorder: 'hover:border-sky-500',
    borderLeft: 'border-l-sky-600',
    textPrimary: 'text-sky-700',
    textDark: 'text-sky-900',
    badgeBg: 'bg-sky-100',
    badgeText: 'text-sky-800',
    badgeBorder: 'border-sky-300',
    progressFill: 'bg-sky-600',
    iconBg: 'bg-sky-100',
    iconText: 'text-sky-700',
  },
  cyan: {
    id: 'cyan',
    name: 'Cian Innovación & Desarrollo',
    hex: '#0891B2',
    bgPrimary: 'bg-cyan-600',
    bgLight: 'bg-cyan-50/70',
    bgLightHover: 'hover:bg-cyan-100/70',
    borderLight: 'border-cyan-200',
    borderPrimary: 'border-cyan-500',
    hoverBorder: 'hover:border-cyan-500',
    borderLeft: 'border-l-cyan-600',
    textPrimary: 'text-cyan-700',
    textDark: 'text-cyan-900',
    badgeBg: 'bg-cyan-100',
    badgeText: 'text-cyan-800',
    badgeBorder: 'border-cyan-300',
    progressFill: 'bg-cyan-600',
    iconBg: 'bg-cyan-100',
    iconText: 'text-cyan-700',
  },
  teal: {
    id: 'teal',
    name: 'Verde Azulado & Bioética',
    hex: '#0D9488',
    bgPrimary: 'bg-teal-600',
    bgLight: 'bg-teal-50/70',
    bgLightHover: 'hover:bg-teal-100/70',
    borderLight: 'border-teal-200',
    borderPrimary: 'border-teal-500',
    hoverBorder: 'hover:border-teal-500',
    borderLeft: 'border-l-teal-600',
    textPrimary: 'text-teal-700',
    textDark: 'text-teal-900',
    badgeBg: 'bg-teal-100',
    badgeText: 'text-teal-800',
    badgeBorder: 'border-teal-300',
    progressFill: 'bg-teal-600',
    iconBg: 'bg-teal-100',
    iconText: 'text-teal-700',
  },
  green: {
    id: 'green',
    name: 'Verde Bosque & Sostenibilidad',
    hex: '#16A34A',
    bgPrimary: 'bg-green-600',
    bgLight: 'bg-green-50/70',
    bgLightHover: 'hover:bg-green-100/70',
    borderLight: 'border-green-200',
    borderPrimary: 'border-green-500',
    hoverBorder: 'hover:border-green-500',
    borderLeft: 'border-l-green-600',
    textPrimary: 'text-green-700',
    textDark: 'text-green-900',
    badgeBg: 'bg-green-100',
    badgeText: 'text-green-800',
    badgeBorder: 'border-green-300',
    progressFill: 'bg-green-600',
    iconBg: 'bg-green-100',
    iconText: 'text-green-700',
  },
  lime: {
    id: 'lime',
    name: 'Lima Biotecnología & Vida',
    hex: '#65A30D',
    bgPrimary: 'bg-lime-600',
    bgLight: 'bg-lime-50/70',
    bgLightHover: 'hover:bg-lime-100/70',
    borderLight: 'border-lime-200',
    borderPrimary: 'border-lime-500',
    hoverBorder: 'hover:border-lime-500',
    borderLeft: 'border-l-lime-600',
    textPrimary: 'text-lime-800',
    textDark: 'text-lime-950',
    badgeBg: 'bg-lime-100',
    badgeText: 'text-lime-900',
    badgeBorder: 'border-lime-300',
    progressFill: 'bg-lime-600',
    iconBg: 'bg-lime-100',
    iconText: 'text-lime-800',
  },
  amber: {
    id: 'amber',
    name: 'Ámbar Negocios & Proyectos',
    hex: '#D97706',
    bgPrimary: 'bg-amber-600',
    bgLight: 'bg-amber-50/70',
    bgLightHover: 'hover:bg-amber-100/70',
    borderLight: 'border-amber-200',
    borderPrimary: 'border-amber-500',
    hoverBorder: 'hover:border-amber-500',
    borderLeft: 'border-l-amber-600',
    textPrimary: 'text-amber-700',
    textDark: 'text-amber-900',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-800',
    badgeBorder: 'border-amber-300',
    progressFill: 'bg-amber-600',
    iconBg: 'bg-amber-100',
    iconText: 'text-amber-700',
  },
  orange: {
    id: 'orange',
    name: 'Naranja Creativo & Media',
    hex: '#EA580C',
    bgPrimary: 'bg-orange-600',
    bgLight: 'bg-orange-50/70',
    bgLightHover: 'hover:bg-orange-100/70',
    borderLight: 'border-orange-200',
    borderPrimary: 'border-orange-500',
    hoverBorder: 'hover:border-orange-500',
    borderLeft: 'border-l-orange-600',
    textPrimary: 'text-orange-700',
    textDark: 'text-orange-900',
    badgeBg: 'bg-orange-100',
    badgeText: 'text-orange-800',
    badgeBorder: 'border-orange-300',
    progressFill: 'bg-orange-600',
    iconBg: 'bg-orange-100',
    iconText: 'text-orange-700',
  },
  yellow: {
    id: 'yellow',
    name: 'Dorado & Economía',
    hex: '#CA8A04',
    bgPrimary: 'bg-yellow-600',
    bgLight: 'bg-yellow-50/70',
    bgLightHover: 'hover:bg-yellow-100/70',
    borderLight: 'border-yellow-200',
    borderPrimary: 'border-yellow-500',
    hoverBorder: 'hover:border-yellow-500',
    borderLeft: 'border-l-yellow-600',
    textPrimary: 'text-yellow-800',
    textDark: 'text-yellow-950',
    badgeBg: 'bg-yellow-100',
    badgeText: 'text-yellow-900',
    badgeBorder: 'border-yellow-300',
    progressFill: 'bg-yellow-600',
    iconBg: 'bg-yellow-100',
    iconText: 'text-yellow-800',
  },
  red: {
    id: 'red',
    name: 'Rojo Carmesí & Liderazgo',
    hex: '#DC2626',
    bgPrimary: 'bg-red-600',
    bgLight: 'bg-red-50/70',
    bgLightHover: 'hover:bg-red-100/70',
    borderLight: 'border-red-200',
    borderPrimary: 'border-red-500',
    hoverBorder: 'hover:border-red-500',
    borderLeft: 'border-l-red-600',
    textPrimary: 'text-red-700',
    textDark: 'text-red-900',
    badgeBg: 'bg-red-100',
    badgeText: 'text-red-800',
    badgeBorder: 'border-red-300',
    progressFill: 'bg-red-600',
    iconBg: 'bg-red-100',
    iconText: 'text-red-700',
  },
  rose: {
    id: 'rose',
    name: 'Rosa Salud & Ciencias Clínicas',
    hex: '#E11D48',
    bgPrimary: 'bg-rose-600',
    bgLight: 'bg-rose-50/70',
    bgLightHover: 'hover:bg-rose-100/70',
    borderLight: 'border-rose-200',
    borderPrimary: 'border-rose-500',
    hoverBorder: 'hover:border-rose-500',
    borderLeft: 'border-l-rose-600',
    textPrimary: 'text-rose-700',
    textDark: 'text-rose-900',
    badgeBg: 'bg-rose-100',
    badgeText: 'text-rose-800',
    badgeBorder: 'border-rose-300',
    progressFill: 'bg-rose-600',
    iconBg: 'bg-rose-100',
    iconText: 'text-rose-700',
  },
  pink: {
    id: 'pink',
    name: 'Rosa Vibrante & Comunicaciones',
    hex: '#DB2777',
    bgPrimary: 'bg-pink-600',
    bgLight: 'bg-pink-50/70',
    bgLightHover: 'hover:bg-pink-100/70',
    borderLight: 'border-pink-200',
    borderPrimary: 'border-pink-500',
    hoverBorder: 'hover:border-pink-500',
    borderLeft: 'border-l-pink-600',
    textPrimary: 'text-pink-700',
    textDark: 'text-pink-900',
    badgeBg: 'bg-pink-100',
    badgeText: 'text-pink-800',
    badgeBorder: 'border-pink-300',
    progressFill: 'bg-pink-600',
    iconBg: 'bg-pink-100',
    iconText: 'text-pink-700',
  },
  fuchsia: {
    id: 'fuchsia',
    name: 'Fucsia Artes & Multimedia',
    hex: '#C026D3',
    bgPrimary: 'bg-fuchsia-600',
    bgLight: 'bg-fuchsia-50/70',
    bgLightHover: 'hover:bg-fuchsia-100/70',
    borderLight: 'border-fuchsia-200',
    borderPrimary: 'border-fuchsia-500',
    hoverBorder: 'hover:border-fuchsia-500',
    borderLeft: 'border-l-fuchsia-600',
    textPrimary: 'text-fuchsia-700',
    textDark: 'text-fuchsia-900',
    badgeBg: 'bg-fuchsia-100',
    badgeText: 'text-fuchsia-800',
    badgeBorder: 'border-fuchsia-300',
    progressFill: 'bg-fuchsia-600',
    iconBg: 'bg-fuchsia-100',
    iconText: 'text-fuchsia-700',
  },
  purple: {
    id: 'purple',
    name: 'Púrpura Educación & Humanidades',
    hex: '#7C3AED',
    bgPrimary: 'bg-purple-600',
    bgLight: 'bg-purple-50/70',
    bgLightHover: 'hover:bg-purple-100/70',
    borderLight: 'border-purple-200',
    borderPrimary: 'border-purple-500',
    hoverBorder: 'hover:border-purple-500',
    borderLeft: 'border-l-purple-600',
    textPrimary: 'text-purple-700',
    textDark: 'text-purple-900',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-800',
    badgeBorder: 'border-purple-300',
    progressFill: 'bg-purple-600',
    iconBg: 'bg-purple-100',
    iconText: 'text-purple-700',
  },
  violet: {
    id: 'violet',
    name: 'Violeta Futuro & Cuántica',
    hex: '#8B5CF6',
    bgPrimary: 'bg-violet-600',
    bgLight: 'bg-violet-50/70',
    bgLightHover: 'hover:bg-violet-100/70',
    borderLight: 'border-violet-200',
    borderPrimary: 'border-violet-500',
    hoverBorder: 'hover:border-violet-500',
    borderLeft: 'border-l-violet-600',
    textPrimary: 'text-violet-700',
    textDark: 'text-violet-900',
    badgeBg: 'bg-violet-100',
    badgeText: 'text-violet-800',
    badgeBorder: 'border-violet-300',
    progressFill: 'bg-violet-600',
    iconBg: 'bg-violet-100',
    iconText: 'text-violet-700',
  },
  indigo: {
    id: 'indigo',
    name: 'Índigo Ciencias Sociales & Leyes',
    hex: '#4F46E5',
    bgPrimary: 'bg-indigo-600',
    bgLight: 'bg-indigo-50/70',
    bgLightHover: 'hover:bg-indigo-100/70',
    borderLight: 'border-indigo-200',
    borderPrimary: 'border-indigo-500',
    hoverBorder: 'hover:border-indigo-500',
    borderLeft: 'border-l-indigo-600',
    textPrimary: 'text-indigo-700',
    textDark: 'text-indigo-900',
    badgeBg: 'bg-indigo-100',
    badgeText: 'text-indigo-800',
    badgeBorder: 'border-indigo-300',
    progressFill: 'bg-indigo-600',
    iconBg: 'bg-indigo-100',
    iconText: 'text-indigo-700',
  },
  slate: {
    id: 'slate',
    name: 'Pizarra Interdisciplinaria',
    hex: '#475569',
    bgPrimary: 'bg-slate-600',
    bgLight: 'bg-slate-50/70',
    bgLightHover: 'hover:bg-slate-100/70',
    borderLight: 'border-slate-200',
    borderPrimary: 'border-slate-500',
    hoverBorder: 'hover:border-slate-500',
    borderLeft: 'border-l-slate-600',
    textPrimary: 'text-slate-700',
    textDark: 'text-slate-900',
    badgeBg: 'bg-slate-100',
    badgeText: 'text-slate-800',
    badgeBorder: 'border-slate-300',
    progressFill: 'bg-slate-600',
    iconBg: 'bg-slate-100',
    iconText: 'text-slate-700',
  },
  zinc: {
    id: 'zinc',
    name: 'Plata Técnica & Control',
    hex: '#52525B',
    bgPrimary: 'bg-zinc-600',
    bgLight: 'bg-zinc-50/70',
    bgLightHover: 'hover:bg-zinc-100/70',
    borderLight: 'border-zinc-200',
    borderPrimary: 'border-zinc-500',
    hoverBorder: 'hover:border-zinc-500',
    borderLeft: 'border-l-zinc-600',
    textPrimary: 'text-zinc-700',
    textDark: 'text-zinc-900',
    badgeBg: 'bg-zinc-100',
    badgeText: 'text-zinc-800',
    badgeBorder: 'border-zinc-300',
    progressFill: 'bg-zinc-600',
    iconBg: 'bg-zinc-100',
    iconText: 'text-zinc-700',
  },
  stone: {
    id: 'stone',
    name: 'Piedra Cálida & Patrimonio',
    hex: '#78716C',
    bgPrimary: 'bg-stone-600',
    bgLight: 'bg-stone-50/70',
    bgLightHover: 'hover:bg-stone-100/70',
    borderLight: 'border-stone-200',
    borderPrimary: 'border-stone-500',
    hoverBorder: 'hover:border-stone-500',
    borderLeft: 'border-l-stone-600',
    textPrimary: 'text-stone-700',
    textDark: 'text-stone-900',
    badgeBg: 'bg-stone-100',
    badgeText: 'text-stone-800',
    badgeBorder: 'border-stone-300',
    progressFill: 'bg-stone-600',
    iconBg: 'bg-stone-100',
    iconText: 'text-stone-700',
  },
};

export function getFacultyTheme(colorKey?: string): FacultyThemeConfig {
  if (!colorKey) return FACULTY_THEMES.emerald;
  const normalized = colorKey.toLowerCase().trim();
  return FACULTY_THEMES[normalized] || FACULTY_THEMES.emerald;
}

export const POPULAR_LUCIDE_SUGGESTIONS = [
  'Building2',
  'Sparkles',
  'GraduationCap',
  'FolderKanban',
  'Layers',
  'Cpu',
  'Code2',
  'Video',
  'Film',
  'Palette',
  'HeartPulse',
  'Briefcase',
  'Globe',
  'Atom',
  'Brain',
  'Bot',
  'Rocket',
  'BookOpen',
  'Scale',
  'ShieldCheck',
];
